### ISSUE TITLE
Some kind of conflict with fugitive/dispatch

### ISSUE THREAD

**Issue by lourenci** [itchyny/vim-qfedit#6]
When I run some fugitive command (`:0Gclog` for example), the quickfix list is cleared when it gets focused.

**For reproduce**:
Just run any command from fugitive (or dispatch.vim) (`:0Gclog`, `:Dispatch`, `:Glog`) that feeds the quickfix list and focus on the quick fix window.

The problem not happens when the quickfix was feed manually nor with those commands above with this plugin disabled.

Thank you for the plugin.

**Comment by itchyny** [comment]
I don't use these plugins but patches are welcome.
See #5 where introduced fugitive support.

**Comment by KSR-Yasuda** [comment]
@lourenci I had experienced this issue and that's why I raised the pull-request https://github.com/itchyny/vim-qfedit/pull/5.
Now, in my environment, it looks working with `:Gclog` command, at least.

The [pull-request](https://github.com/itchyny/vim-qfedit/pull/5) aimed
`qfedit` plugin to support `fugitive://****` file path that is introduced by `fugitive` plugin.
Without it, `qfedit` removes `fugitive` items from quickfix list because they're recognized as invalid items.

If you can take a look into the plugin source,
check the item list `b:qfedit_items`; and around the filepath modification of the pull-request.
Not being an expert of `qfedit` or `fugitive` plugin, I may being overlooking something.

Recently I don't look `:Gclog` carefully.
Now I do mostly use `:G log` command instead, that does not use quickfix list.
